'use strict';
const D=window.EXAM_DATA,C=window.ExamCore,app=document.querySelector('#app');
const items=D.items.filter(i=>i.active&&typeof i.correctJudgment==='boolean'), byKey=new Map(items.map(i=>[i.sourceItemKey,i]));
const keys=new Set([...byKey.keys(),...D.choices.map(q=>'choice:'+q.id)]);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const card=x=>'<section class="card">'+x+'</section>';
const button=(action,text,cls='secondary',extra='')=>`<button class="${cls}" data-action="${action}" ${extra}>${text}</button>`;
let state,progress={},screen='home',startedAt=Date.now(),busy=false;
function notify(s){document.querySelector('#notice').textContent=s;}
function save(next){const json=JSON.stringify(next);if(window.Android){if(!Android.saveState(json))throw Error('端末への保存に失敗しました。空き容量を確認してください。');}else localStorage.setItem('exam-offline-v1',json);state=next;progress=C.progress(state.attempts);}
function init(){try{const saved=window.Android?Android.readState():localStorage.getItem('exam-offline-v1');state=saved?JSON.parse(saved):{schemaVersion:1,attempts:[],session:null,examDate:''};if(state.schemaVersion!==1||!Array.isArray(state.attempts))throw Error('保存データの形式が不正です。');state.attempts=state.attempts.map((a,i)=>C.validateAttempt(a,keys,i));progress=C.progress(state.attempts);home();}catch(e){app.innerHTML=card('<h2>保存データを読み込めません</h2><p>'+esc(e.message)+'</p><p>データを消さずに、バックアップを書き出してください。</p>'+button('raw-backup','保存データを書き出す'));}}
function due(p){return !!p&&(Date.parse(p.nextReviewAt)<=Date.now()||p.masteryStatus==='RELEARNING');}
function effectiveDue(p){if(!p)return false;if(due(p))return true;if(!state.examDate)return false;const deadline=Date.parse(state.examDate+'T00:00:00+09:00')-3*86400000;return deadline>Date.parse(p.lastAnsweredAt)&&Date.now()>=deadline;}
function home(){screen='home';const answered=items.filter(i=>progress[i.sourceItemKey]).length,review=items.filter(i=>i.reviewEligible&&effectiveDue(progress[i.sourceItemKey])).length;const all=state.attempts,correct=all.filter(a=>a.isCorrect).length;
app.innerHTML=`<section class="card hero"><p class="eyebrow">OFFLINE STUDY</p><h2>スマホだけで、いつでも復習</h2><p>学習済み ${answered} / ${items.length}問</p><progress value="${answered}" max="${items.length}"></progress><p class="muted">回答 ${all.length}回 ・ 正答率 ${all.length?Math.round(correct/all.length*100):0}%</p></section>`+(state.session?card('<h2>前回の演習</h2><p>'+state.session.index+' / '+state.session.keys.length+'問まで進めました。</p>'+button('resume','続きから学習')):'')+card('<h2>今日の復習</h2><p>復習対象 '+review+'問</p>'+button('review','復習を始める','primary'))+card('<h2>演習</h2>'+button('practice','問題を選んで演習','secondary wide')+button('choice','市政知識の五択演習','secondary wide'))+card('<h2>履歴の引き継ぎ</h2><p>Web版の回答ログCSVを取り込めます。現在の履歴に追加し、同じ問題・日時の重複を省きます。</p>'+button('import','CSV・バックアップを取り込む'));
}
function practice(){screen='practice';app.innerHTML=card('<h2>演習の設定</h2><label class="field">科目<select id="subject"><option value="">全科目</option>'+D.subjects.map(s=>`<option>${esc(s)}</option>`).join('')+'</select></label><label class="field">対象<select id="filter"><option value="all">全問</option><option value="new">未回答</option><option value="wrong">前回誤答</option><option value="low">正答率70%未満</option><option value="unsure">前回「迷った」</option><option value="review">復習対象</option></select></label><label class="field">問題数<select id="count"><option value="20">20問</option><option value="50">50問</option><option value="100">100問</option><option value="all">全問</option></select></label><label class="field"><span><input id="shuffle" type="checkbox" checked> ランダム順</span></label><label class="field"><span><input id="fast" type="checkbox"> 高速周回（自信を持って正解したら次へ）</span></label>'+button('start','演習を始める','primary wide'));
}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function start(mode){let list;if(mode==='choice')list=D.choices.map(q=>'choice:'+q.id);else{let subject='',filter='review',count='all',random=true,fast=false;if(mode==='practice'){subject=document.querySelector('#subject').value;filter=document.querySelector('#filter').value;count=document.querySelector('#count').value;random=document.querySelector('#shuffle').checked;fast=document.querySelector('#fast').checked;}
list=items.filter(i=>{if(subject&&i.subject!==subject)return false;const p=progress[i.sourceItemKey];return filter==='all'||filter==='new'&&!p||filter==='wrong'&&p?.lastResult===false||filter==='low'&&p&&p.correctCount/p.attemptsCount<.7||filter==='unsure'&&p?.lastWasUnsure===true||filter==='review'&&i.reviewEligible&&effectiveDue(p);}).map(i=>i.sourceItemKey);if(random)shuffle(list);if(count!=='all')list=list.slice(0,Number(count));if(!list.length){notify('該当する問題がありません。');return;}if(state.session&&!confirm('途中の演習を終了して、新しく始めますか？回答履歴は残ります。'))return;save({...state,session:{keys:list,index:0,result:null,correct:0,fast}});study();return;}
if(state.session&&!confirm('途中の演習を終了して、五択演習を始めますか？'))return;save({...state,session:{keys:list,index:0,result:null,correct:0,fast:false}});study();}
function study(){screen='study';const s=state.session;if(!s)return home();if(s.index>=s.keys.length)return complete();const key=s.keys[s.index],choice=key.startsWith('choice:'),i=choice?D.choices.find(q=>'choice:'+q.id===key):byKey.get(key);if(!i)throw Error('問題が見つかりません。');const ctx=choice?null:D.contexts[i.id];
const pre=choice?i.context:ctx?.questionContext||'',ref=choice?i.referenceDate:ctx?.referenceDateLabel||'';let body=`<p class="eyebrow">${choice?'市政知識・五択':esc(i.subject)} ・ ${s.index+1} / ${s.keys.length}</p><progress value="${s.index}" max="${s.keys.length}"></progress>`+(pre?`<p class="context">${esc(pre)}</p>`:'')+(ref?`<p class="muted small">${esc(ref)}</p>`:'')+`<p class="question">${esc(choice?i.prompt:i.statement)}</p>`;
if(!s.result){body+='<label class="field"><span><input id="unsure" type="checkbox"> 迷った</span></label>';body+=choice?'<div class="choice-list">'+i.choices.map((o,j)=>button('answer',`<b>${j+1}</b><span>${esc(o.text)}</span>`,'choice-option',`data-value="${j+1}"`)).join('')+'</div>':'<div class="answers">'+button('answer','○ 正しい','answer true','data-value="true"')+button('answer','× 誤り','answer false','data-value="false"')+'</div>';}
else{body+=`<h2 class="${s.result.isCorrect?'result-ok':'result-ng'}">${s.result.isCorrect?'正解':'不正解'} ・ 正答 ${choice?i.correctChoice:(i.correctJudgment?'○':'×')}</h2>`+(s.result.wasUnsure?'<span class="badge">迷った</span>':'');if(choice)body+=i.choices.map((o,j)=>`<div class="choice-explanation"><b>${j+1}${i.correctChoice===j+1?'（正答）':''}</b><p>${esc(o.text)}</p><p>${esc(o.explanation)}</p><small>${esc(o.source)}</small></div>`).join('');else{body+=`<div class="explanation">${esc(i.explanation)}</div>`;const h=D.history[i.id];if(h){body+=`<p class="small muted">過去問：同一論点 ${h.exact?.yearCount??0}年度 ／ 条文単位 ${h.relatedArticles?.yearCount??0}年度</p>`;}body+=button('related-text','この科目の教材を読む');}body+=button('next',s.index+1===s.keys.length?'結果を見る':'次の問題へ','primary wide');}
app.innerHTML=card(body)+button('home','中断してホームへ','ghost wide');startedAt=Date.now();scrollTo(0,0);}
function answer(value){const s=state.session;if(!s||s.result)return;const key=s.keys[s.index],choice=key.startsWith('choice:'),i=choice?D.choices.find(q=>'choice:'+q.id===key):byKey.get(key);const selected=choice?Number(value):value==='true';const result={sourceItemKey:key,answeredAt:new Date().toISOString(),isCorrect:selected===(choice?i.correctChoice:i.correctJudgment),wasUnsure:document.querySelector('#unsure').checked,responseMs:Date.now()-startedAt};const next={...s,result,correct:s.correct+(result.isCorrect?1:0)};save({...state,attempts:[...state.attempts,result],session:next});if(s.fast&&result.isCorrect&&!result.wasUnsure)nextQuestion();else study();}
function nextQuestion(){const s=state.session;if(!s?.result)return;save({...state,session:{...s,index:s.index+1,result:null}});study();}
function complete(){screen='complete';const s=state.session;app.innerHTML=card('<h2>演習完了</h2><p class="big">'+s.correct+' / '+s.keys.length+'問 正解</p><p>回答履歴は端末に保存しました。</p>'+button('finish','ホームへ','primary wide'));}
function texts(subject='',query=''){screen='texts';const selected=subject||D.subjects[0],book=D.handbooks[selected],topics=book.topics.filter(t=>!query||(t.searchText||t.title).includes(query));app.innerHTML=card('<h2>教材</h2><label class="field">科目<select id="text-subject">'+D.subjects.map(s=>`<option ${s===selected?'selected':''}>${esc(s)}</option>`).join('')+'</select></label><input class="search" id="text-query" placeholder="教材内を検索" value="'+esc(query)+'">'+button('search-text','検索','secondary wide')+'<div class="handbook-topics">'+topics.map(t=>button('topic',esc(t.title),'ghost',`data-subject="${esc(selected)}" data-id="${esc(t.id)}"`)).join('')+'</div>');scrollTo(0,0);}
function topic(subject,id){screen='topic';const t=D.handbooks[subject].topics.find(t=>t.id===id);app.innerHTML=card('<h2>'+esc(t.title)+'</h2><div class="handbook-body" id="book-content"></div>'+button('texts','教材一覧へ'));const template=document.createElement('template');template.innerHTML=t.html;template.content.querySelectorAll('script,iframe,object,embed,form,style,link').forEach(n=>n.remove());template.content.querySelectorAll('*').forEach(n=>{for(const a of [...n.attributes])if(/^on/i.test(a.name)||['src','srcdoc','href','style'].includes(a.name))n.removeAttribute(a.name);});document.querySelector('#book-content').append(template.content);scrollTo(0,0);}
function stats(){screen='stats';let html='<h2>学習状況</h2>';for(const subject of D.subjects){const pool=items.filter(i=>i.subject===subject),attempts=state.attempts.filter(a=>byKey.get(a.sourceItemKey)?.subject===subject),studied=pool.filter(i=>progress[i.sourceItemKey]);html+=`<div class="stats-row"><span>${esc(subject)}<br><small>学習済み ${studied.length}/${pool.length}問</small></span><span>${attempts.length}回<br>${attempts.length?Math.round(attempts.filter(a=>a.isCorrect).length/attempts.length*100)+'%':'—'}</span></div>`;}const weak=items.filter(i=>progress[i.sourceItemKey]).sort((a,b)=>{const pa=progress[a.sourceItemKey],pb=progress[b.sourceItemKey];return pa.correctCount/pa.attemptsCount-pb.correctCount/pb.attemptsCount;}).slice(0,20);html+='<h3>正答率の低い問題</h3>'+weak.map(i=>{const p=progress[i.sourceItemKey];return `<details><summary>${esc(i.subject)} ${Math.round(p.correctCount/p.attemptsCount*100)}% ・ ${p.attemptsCount}回</summary><p>${esc(i.statement)}</p><p>${esc(i.explanation)}</p></details>`;}).join('');app.innerHTML=card(html);}
function settings(){screen='settings';app.innerHTML=card('<h2>保存・履歴移行</h2><p>回答履歴 '+state.attempts.length+'件。端末内に保存しています。</p>'+button('import','CSV・バックアップを取り込む','secondary wide')+button('backup','バックアップJSONを書き出す','secondary wide')+button('export-csv','回答ログCSVを書き出す','secondary wide')+'<p class="small muted">アンインストールやアプリのデータ消去をすると履歴が消えます。機種変更の前にもバックアップを保存してください。</p>')+card('<h2>試験日</h2><p>試験3日前以降は、次の復習日が先の問題も復習対象にします。</p><label class="field"><input id="exam-date" type="date" value="'+esc(state.examDate||'')+'"></label>'+button('save-settings','保存'))+card('<h2>このアプリについて</h2><p>○× '+items.length+'問・五択 '+D.choices.length+'問・6科目の教材を同梱しています。</p><p>CSVには選んだ○×そのものが含まれないため、正誤・迷った・日時・回答時間を引き継ぎます。復習予定は既存の復習ルールで再計算します。</p>');}
function receiveImport(text){try{if(text.length>20*1024*1024)throw Error('ファイルが大きすぎます。');let incoming,backup=null;if(text.trimStart().startsWith('{')){backup=JSON.parse(text);if(backup.schemaVersion!==1||!Array.isArray(backup.attempts))throw Error('バックアップの形式が不正です。');incoming=backup.attempts;}else incoming=C.parseCSV(text);const result=C.mergeAttempts(state.attempts,incoming,keys);if(!confirm(`${incoming.length}件を確認しました。${result.added}件を追加し、${result.duplicates}件の重複を省きます。取り込みますか？`)){notify("取り込みをキャンセルしました。履歴は変更していません。");return;}save({...state,attempts:result.attempts,examDate:state.examDate||backup?.examDate||''});notify(`${result.added}件の履歴を取り込みました。重複 ${result.duplicates}件。`);home();}catch(e){notify('取り込みを中止しました：'+e.message);}}
window.receiveImport=receiveImport;window.nativeNotice=notify;
function exportFile(name,type,text){if(window.Android){Android.exportFile(name,type,text);return;}const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportCSV(){const headers=['answeredAt','subject','sourceItemKey','question','questionContext','referenceDateLabel','isCorrect','wasUnsure','responseMs','weaknessScore','recentAccuracy','improvement'];const rows=state.attempts.map(a=>{const i=byKey.get(a.sourceItemKey),q=D.choices.find(q=>'choice:'+q.id===a.sourceItemKey),ctx=i?D.contexts[i.id]:null;return [a.answeredAt,i?.subject||'市政知識',a.sourceItemKey,i?.statement||q?.prompt||'',ctx?.questionContext||q?.context||'',ctx?.referenceDateLabel||q?.referenceDate||'',a.isCorrect,a.wasUnsure,a.responseMs??'','','',''];});const encode=r=>r.map(x=>'"'+String(x).replace(/"/g,'""')+'"').join(',');exportFile('examapp-answer-log.csv','text/csv','\uFEFF'+[headers,...rows].map(encode).join('\r\n'));}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||busy)return;busy=true;try{switch(b.dataset.action){case 'home':home();break;case 'practice':practice();break;case 'start':start('practice');break;case 'review':start('review');break;case 'choice':start('choice');break;case 'resume':study();break;case 'answer':answer(b.dataset.value);break;case 'next':nextQuestion();break;case 'finish':save({...state,session:null});home();break;case 'texts':texts();break;case 'search-text':texts(document.querySelector('#text-subject').value,document.querySelector('#text-query').value);break;case 'topic':topic(b.dataset.subject,b.dataset.id);break;case 'related-text':texts(byKey.get(state.session.keys[state.session.index]).subject);break;case 'stats':stats();break;case 'settings':settings();break;case 'save-settings':save({...state,examDate:document.querySelector('#exam-date').value});notify('試験日を保存しました。');break;case 'import':if(window.Android)Android.importFile();else document.querySelector('#import-file').click();break;case 'backup':exportFile('examapp-backup.json','application/json',JSON.stringify(state,null,2));break;case 'raw-backup':exportFile('examapp-recovery.json','application/json',window.Android?Android.readState():localStorage.getItem('exam-offline-v1')||'{}');break;case 'export-csv':exportCSV();break;}}catch(e){notify(e.message);}finally{busy=false;}});
document.querySelector('#import-file').addEventListener('change',async e=>{try{const file=e.target.files[0];if(file)receiveImport(await file.text());}catch(e){notify(e.message);}finally{e.target.value='';}});
document.addEventListener('change',e=>{if(e.target.id==='text-subject')texts(e.target.value);});
window.handleBack=()=>{if(screen==='home')return false;home();return true;};
init();
